openapi: 3.0.1
info:
  title: Benefits Registration Service
  description: |
    This service provides APIs to register new Benefit schemes in the system.
  contact:
    name: Benefits Provider
    email: test@yopmail.com
  version: 1.0.0

paths:
  /benefits/v1/_search:
    post:
      tags:
       - Benefits Registration Application
      summary: Get the list of Benefits Registration applications
      description: |
        1. Search and get Benefits Registration applications(s) based on defined search criteria.
        2. In case multiple parameters are passed, Benefits Registration applications will be searched as an AND combination of all the parameters.
      requestBody:
        description: Parameter to carry Request metadata in the request body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BenefitsSearchCriteria'
        required: false
      responses:
        200:
          description: Benefits Registration applications retrieved successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BenefitsRegistrationRequest'
        400:
          description: Invalid input
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: requestInfo

  /benefits/v1/_create:
    post:
      tags:
       - Benefits Registration Application
      summary: Create new Benefits Registration Application
      description: "To create new Benefits registration applications in the system. A single Benefit can be added at one time."
      requestBody:
        description: Details for the new Benefits Registration Application(s) + RequestInfo metadata.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BenefitsRegistrationRequest'
        required: true
      responses:
        201:
          description: ResponseInfo with Benefits Registration Application(s) created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BenefitsRegistrationResponse'
        400:
          description: Benefits Registration Application creation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: BenefitsRegistrationRequest

  /benefits/v1/_update:
    post:
      tags:
       - Benefits Registration Application
      summary: Update existing Benefits Registration Applications
      description: |
        To update existing Benefits registration applications in the system. A single Benefit can be updated at one time.
      requestBody:
        description: Details for the updated Benefits Registration Applications + RequestInfo metadata.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BenefitsRegistrationRequest'
        required: true
      responses:
        201:
          description: ResponseInfo with Benefits Registration Application(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BenefitsRegistrationResponse'
        400:
          description: Benefits Registration Application update failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: BenefitsRegistrationRequest

  /benefits/v1/_discard:
    post:
      tags:
       - Benefits Registration Application
      summary: Delete existing Benefits Registration Applications
      description: |
        To delete existing Benefits registration applications in the system. A single Benefit can be deleted at one time.
      requestBody:
        description: Details for the Benefits Discard Application(s) + RequestInfo metadata.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BenefitsDiscardRequest'
        required: true
      responses:
        201:
          description: ResponseInfo with Benefits Registration Application(s) deleted successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BenefitsDiscardResponse'
        400:
          description: Benefits Registration Application deletion failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: BenefitsDiscardRequest

components:
  schemas:
    Benefit:
      type: object
      required:
        - benefitName
        - benefitProvider
        - sponsors
        - isDraft
      properties:
        benefitId:
          type: string
          description: Unique Identifier of the Benefit
        benefitName:
          type: string
          maxLength: 128
          description: Name of the Benefit
        benefitProvider:
          type: string
          maxLength: 128
          description: Name of the provider offering the benefit
        sponsors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Sponsor'
          description: List of sponsors
        benefitDescription:
          type: string
          maxLength: 256
          description: Description of the Benefit
        isDraft:
          type: boolean
          description: Whether to be saved as a draft.
        eligibility:
          $ref: '#/components/schemas/EligibilityCriteria'
        financialInformation:
          $ref: '#/components/schemas/FinancialInformation'
        otherTermsAndConditions:
          $ref: '#/components/schemas/OtherTermsAndConditions'

    Sponsor:
      type: object
      required:
        - benefitSponsor
        - sponsorEntity
        - sponsorShare
      properties:
        benefitSponsor:
          type: string
          description: Name of the sponsor
        sponsorEntity:
          type: string
          enum: 
            - Non-Profit
            - Corporate
            - Government
            - Institute
            - Foundation
            - Individual
          description: Type of sponsor entity (e.g., Corporate, Non-Profit, Government)
        sponsorShare:
          type: number
          description: Percentage share of the sponsor
      description: Additional sponsor details.

    EligibilityCriteria:
      type: object
      properties:
        gender:
          type: string
          enum: 
            - Male
            - Female
            - Both
          description: Eligibility based on gender
        class:
          type: string
          maxLength: 128
          description: Class level for eligibility
        marks:
          type: string
          maxLength: 128
          description: Marks criteria for eligibility (e.g., "Above 70%").
        minQualification:
          type: string
          maxLength: 128
          description: Minimum qualification required for eligibility
        fieldOfStudy:
          type: string
          maxLength: 128
          description: Field of study eligible for the benefit
        attendancePercentage:
          type: string
          maxLength: 128
          description: Attendance percentage criteria for eligibility (e.g., "Above 70%")
        annualIncome:
          type: string
          maxLength: 128
          description: Annual income criteria for eligibility (e.g., "Below 5,00,000/-")
        caste:
          type: array
          items:
            type: string
            enum: 
              - General
              - SC
              - ST
              - OBC
          description: Caste-based eligibility
        disability:
          type: boolean
          description: Whether the benefit is applicable to students with disabilities
        domicile:
          type: string
          maxLength: 128
          description: Domicile eligibility (e.g., "Maharashtra")
        studentType:
          type: string
          enum:
            - dayscholar
            - hosteler
            - both
          description: Type of student eligible for the benefit
        age:
          type: integer
          description: Age eligibility for the benefit
        eligibleChildren:
          type: integer
          description: Maximum number of children eligible

    FinancialInformation:
      type: object
      properties:
        parentOccupation:
          type: string
          maxLength: 128
          description: Parent's occupation for financial criteria
        amountPerBeneficiaryCategory:
          type: object
          properties:
            beneficiaryCaste:
              type: string
              enum: 
                - General
                - SC
                - ST
                - OBC
              description: Caste of the beneficiary
            beneficiaryType:
              type: string
              enum:
                - dayscholar
                - hosteler
                - both
              description: Type of beneficiary
            beneficiaryCategory:
              type: string
              description: Category of the beneficiary
            beneficiaryAmount:
              type: number
              format: double
              description: Amount allotted for the beneficiary
        maxBeneficiaryLimit:
          type: boolean
          description: Whether there is a maximum limit to beneficiaries allowed
        maxBeneficiaryAllowed:
          type: integer
          description: Maximum number of beneficiaries allowed

    OtherTermsAndConditions:
      type: object
      properties:
        allowWithOtherBenefit:
          type: boolean
          description: Whether the benefit is applicable with other schemes for a specific academic year
        allowForOneYearIfFailed:
          type: boolean
          description: Whether the benefit is applicable for one year if the student fails
        applicationDeadlineDate:
          type: string
          format: date
          description: Deadline date for benefit application submission
        extendedDeadlineDate:
          type: string
          format: date
          description: Extended deadline date for benefit application submission
        validTillDate:
          type: string
          format: date
          description: Validity date for the benefit
        autoRenewalApplicable:
          type: boolean
          description: Whether renewal is applicable for the benefit 

    BenefitsRegistrationRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        Benefit:
          type: array
          items:
            $ref: '#/components/schemas/Benefit'
          description: Contains Benefit details
      description: Contract class to receive request for registration.

    BenefitsDiscardRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        BenefitId:
          type: string
          description: Contains Benefit ID
      description: Contract class to discard benefit application.

    BenefitsDiscardResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        message:
          type: string
          description: Confirmation message of deletion.
      description: Contract class to send response after discard.

    BenefitsRegistrationResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        Benefit:
          type: array
          items:
            $ref: '#/components/schemas/Benefit'
          description: Contains Benefit details
      description: Contract class to send response.

    BenefitsSearchCriteria:
      type: object
      properties:
        status:
          type: string
          description: Search based on status.
        benefitName:
          type: array
          description: Names of benefits
          items:
            type: string
        benefitProviderIds:
          type: array
          description: List of provider IDs
          items:
            type: string
        applicationNumber:
          type: string
          maxLength: 64
          minLength: 2
          description: Unique application number for the Benefits Registration Application

x-api-id: org.egov.birth.services
x-common-path: https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml
