name: Build and Push Docker Image for Backend Application

on:
  push:
    branches:
      - features.benefitcreateupdate  # Trigger on push to the feature branch
  pull_request:
    branches:
      - features.benefitcreateupdate  # Trigger on PR to the feature branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Hub credentials
      - name: Set up Docker Hub credentials
        run: |
          echo "Devops@1997" | docker login --username prsm323 --password-stdin

      # Step 3: Build and push Docker image for backend/application
      - name: Build and push Docker image for backend/application
        run: |
          IMAGE_TAG="v1.0.0-$(date +'%Y%m%d-%H%M%S')"  # Set a unique image tag based on date-time
          echo "Building Docker image for backend/application with tag $IMAGE_TAG"
          
          # Build the Docker image from the backend/application folder
          docker build -t prsm323/backend/application:$IMAGE_TAG ./backend/application || { echo 'Docker build failed'; exit 1; }

          echo "Pushing Docker image prsm323/application:$IMAGE_TAG"
          
          # Push the Docker image to Docker Hub
          docker push prsm323/application:$IMAGE_TAG || { echo 'Docker push failed'; exit 1; }

          echo "Successfully pushed Docker image prsm323/application:$IMAGE_TAG"
