name: Build and Push Docker Image for Backend Application

on:
  push:
    branches:
      - features.benefitcreateupdate
  pull_request:
    branches:
      - features.benefitcreateupdate

jobs:
  build-and-push-application:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Hub credentials using GitHub Secrets
      - name: Set up Docker Hub credentials
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build Docker image
      - name: Build Docker image for backend/application
        run: |
          IMAGE_TAG="v1.0.0-$(date +'%Y%m%d-%H%M%S')"  # Set a unique image tag based on date-time
          FULL_IMAGE_TAG="prsm323/application:$IMAGE_TAG"  # Full image tag with the correct path
          
          echo "Building Docker image for prsm323/application with tag $FULL_IMAGE_TAG"
          
          # Build the Docker image from the backend/application folder
          docker build -t $FULL_IMAGE_TAG ./backend/application || { echo 'Docker build failed'; exit 1; }

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          if [ -z "$FULL_IMAGE_TAG" ]; then
            echo "FULL_IMAGE_TAG is empty, exiting."
            exit 1
          fi
          
          echo "Pushing Docker image $FULL_IMAGE_TAG to Docker Hub"
          docker push $FULL_IMAGE_TAG || { echo 'Docker push failed'; exit 1; }

      # Step 5: Final success message
      - name: Final success message
        run: |
          echo "Successfully built and pushed Docker image: $FULL_IMAGE_TAG"
